name = "autun-news-api"
main = "worker.js"
compatibility_date = "2024-05-01"

[vars]
BASE_URL = "https://www.autun-infos.com"

# Déclencher le worker sur une route personnalisée
# Remplacer "your-account" par votre ID de compte Cloudflare
# [triggers]
# routes = ["api.example.com/autun-news/*"]

[build]
command = "npm run build" 